MODEL:
  NUM_CLASSES: 6
  META_ARCHITECTURE: 'SSDTMAPANDetector'
  BOX_HEAD:
    #    PREDICTOR: 'SSDLiteBoxPredictor'
    PREDICTOR: 'SSDBoxPredictor'
  #    NAME: 'SSDBoxRPNHead'
  BACKBONE:
    NAME: 'darknet_stam_pan'
    OUT_CHANNELS: (256, 512, 1024)
  PRIORS:
    FEATURE_MAPS: [ 40, 20, 10 ]
    STRIDES: [ 8, 16, 32 ]
    MIN_SIZES: [ 20, 60, 105 ]
    MAX_SIZES: [ 50, 105, 150 ]
    ASPECT_RATIOS: [ [ 2, 3 ], [ 2, 3 ], [ 2, 3 ] ]
    BOXES_PER_LOCATION: [ 6, 6, 6 ]
INPUT:
  IMAGE_SIZE: 320
DATASETS:
  TRAIN: ("dark_vid_train", "dark_vid_val")
  TEST: ("dark_vid_test", )
SOLVER:
  NUM_PREV_CLIPS: 5
  MAX_ITER: 300000
  LR_STEPS: [ 18000 ]
  GAMMA: 0.5
  BATCH_SIZE: 16
  LR: 1e-3

OUTPUT_DIR: 'outputs/5_classes_0823'
